return {
	["StickyScript"] = "https://raw.githubusercontent.com/ChipLag/rb/main/universal/sticky.lua",
	["StickyFlight"] = "https://raw.githubusercontent.com/ChipLag/rb/main/universal/stickyfling.lua",
	["Security Cameras (BUGGY)"] = "https://raw.githubusercontent.com/ChipLag/rb/main/universal/securitycam.lua",
	["Simple Infinite Jump"] = "https://raw.githubusercontent.com/ChipLag/rb/main/universal/simpleinfjump.lua",
	["Nameless Admin"] = "https://raw.githubusercontent.com/FilteringEnabled/NamelessAdmin/main/Source",
	["Infinite Yield"] = "https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source",
	["[NEW] UIs"] = "https://raw.githubusercontent.com/ChipLag/rb/main/srruis.lua",
	["[NEW] SRR Script"] = "https://raw.githubusercontent.com/ChipLag/rb/main/srr/srr_hub.lua",
}
